apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "skmz.fullname" . }}
  labels:
    {{- include "skmz.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.ClassName }}
  {{- range .Values.ingress.hosts }}
  rules:
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - backend:
              service:
                name: {{ include "skmz.fullname" . }}-frontend-svc
                port:
                  number: 80
            path: {{ .path }}
            pathType: {{ .pathType }}
          {{ end }}
  {{ end }}
  tls:
    {{ range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}